name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js and Yarn v1
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: corepack disable  # ensures Yarn v3 (Berry) is NOT used
      - run: npm install -g yarn@1.22.19  # install stable Yarn v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run hardhat node, deploy contracts (& generate contracts typescript output)
        run: yarn chain & yarn deploy

      - name: Run hardhat lint
        run: yarn hardhat:lint --max-warnings=0

      - name: Run nextjs lint
        run: yarn next:lint --max-warnings=0

      - name: Check typings on nextjs
        run: yarn next:check-types